export enum divIds {
    DIGIT = 'digitButtons',
    DOT = 'dot',
    ZERO = 'zeroButton',
    EQUALITY = 'equality',
    BINARY_OPERATORS = 'binaryOperators',
    UNARY_OPERATORS = 'unaryOperators',
    BRACKETS = 'brackets',
    ERASE = 'erase',
    FUNCTIONS = 'functions',
    FUNCTIONS_DROPDOWN = 'functionsDropdown',
    ARROWS = 'arrows',
    INPUT = 'inputDiv',
    OUTPUT = 'outputDiv',
}